### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by jmpas** [Qualy-org/qualy-full#4]

**Comment by willianjusten** [comment]
Lol, you copied whole readme ahauaua
Change that ASAP.

**Comment by ftonato** [comment]
In the _README_ file there's a link to [.editorconfig](https://github.com/frontendbr/eventos/blob/skeleton/.editorconfig) of project **(frontendbr/skeleton)**, but this is a private repository and we don't have access to it.

**Comment by willianjusten** [comment]
Everything will be changed, relax =)

**Comment by gabrielgodoy-zz** [comment]
Fixed Readme

**Comment by ftonato** [comment]
**Correct installation process**

``` sh
# Clone this repository
$ git clone https://github.com/Qualy-org/qualy-full.git
$ cd qualy-full

# install dependencies
$ npm install
```

/cc @Nipher @willianjusten @gabrielgodoy
